
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EmmanuelSal
 */
public class Activity2 extends javax.swing.JFrame {

    double firstnum = 0 , secondnum = 0 , result = 0;
    String operations;
    
    public Activity2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        Calculator = new javax.swing.JPanel();
        show = new javax.swing.JTextField();
        calClr = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        div = new javax.swing.JButton();
        eql = new javax.swing.JButton();
        period = new javax.swing.JButton();
        nega = new javax.swing.JButton();
        sqr = new javax.swing.JButton();
        three1 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        cal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dateChoser = new datechooser.beans.DateChooserCombo();
        ok = new javax.swing.JButton();
        labelR = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTextArea();
        ger = new javax.swing.JButton();
        clr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setIconImages(null);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Activity_2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME:");

        name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date");

        Calculator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));

        show.setEditable(false);
        show.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        show.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        show.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        show.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                showKeyTyped(evt);
            }
        });

        calClr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        calClr.setText("CLR");
        calClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calClrActionPerformed(evt);
            }
        });

        one.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        four.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        seven.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        zero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        plus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        minus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        mult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mult.setText("*");
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });

        div.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        eql.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        eql.setText("=");
        eql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqlActionPerformed(evt);
            }
        });

        period.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        period.setText(".");
        period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodActionPerformed(evt);
            }
        });

        nega.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nega.setText("±");
        nega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negaActionPerformed(evt);
            }
        });

        sqr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sqr.setText("√ ");
        sqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrActionPerformed(evt);
            }
        });

        three1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        three1.setText("^");
        three1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalculatorLayout = new javax.swing.GroupLayout(Calculator);
        Calculator.setLayout(CalculatorLayout);
        CalculatorLayout.setHorizontalGroup(
            CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show)
                    .addGroup(CalculatorLayout.createSequentialGroup()
                        .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalculatorLayout.createSequentialGroup()
                                .addComponent(one)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(three))
                            .addGroup(CalculatorLayout.createSequentialGroup()
                                .addComponent(nega)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sqr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(three1))
                            .addGroup(CalculatorLayout.createSequentialGroup()
                                .addComponent(four)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(five)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(six))
                            .addGroup(CalculatorLayout.createSequentialGroup()
                                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CalculatorLayout.createSequentialGroup()
                                        .addComponent(seven)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eight))
                                    .addGroup(CalculatorLayout.createSequentialGroup()
                                        .addComponent(zero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(period, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eql, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nine, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(18, 18, 18)
                        .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calClr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CalculatorLayout.setVerticalGroup(
            CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calClr)
                    .addComponent(nega)
                    .addComponent(sqr)
                    .addComponent(three1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plus)
                    .addComponent(three)
                    .addComponent(two)
                    .addComponent(one))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four)
                    .addComponent(five)
                    .addComponent(six)
                    .addComponent(minus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seven)
                    .addComponent(eight)
                    .addComponent(nine)
                    .addComponent(mult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(div)
                    .addComponent(zero)
                    .addComponent(eql)
                    .addComponent(period))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        time.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("Time");

        cal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cal.setText("CALCULATOR");
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("QUIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATE OF BIRTH:");

        dateChoser.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChoser.setCalendarPreferredSize(new java.awt.Dimension(400, 180));
    dateChoser.setNothingAllowed(false);
    dateChoser.setFormat(2);
    dateChoser.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);

    ok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    ok.setText("SHOW");
    ok.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            okActionPerformed(evt);
        }
    });

    labelR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    labelR.setForeground(new java.awt.Color(255, 255, 255));
    labelR.setText("RESULT");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(date)
                                .addComponent(time))
                            .addGap(13, 13, 13))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelR)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Calculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addContainerGap())
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dateChoser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ok)
                    .addContainerGap(287, Short.MAX_VALUE))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(date)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(time)
            .addGap(21, 21, 21)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2))
                .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ok))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(labelR)
                    .addGap(50, 50, 50))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(Calculator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(cal))
            .addContainerGap())
    );

    txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtActionPerformed(evt);
        }
    });
    txt.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            txtKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txtKeyTyped(evt);
        }
    });

    table.setEditable(false);
    table.setColumns(20);
    table.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
    table.setRows(5);
    jScrollPane1.setViewportView(table);

    ger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    ger.setText("GENERATE");
    ger.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            gerActionPerformed(evt);
        }
    });

    clr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    clr.setText("CLEAR TEXT");
    clr.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            clrActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(ger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(21, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(ger)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(clr)
            .addGap(21, 21, 21)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(90, 90, 90))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("EEEEEE, MMM dd yyyy");
        date.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
       
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
        time.setText(s.format(d));
            }
            
        }
        ).start();
        
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        showDate();
        showTime();
        labelR.hide();
    
    }//GEN-LAST:event_formWindowActivated

    private void calClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calClrActionPerformed
        show.setText(null);
    }//GEN-LAST:event_calClrActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
      String Enternum = show.getText()+three.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
         String Enternum = show.getText()+four.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
       String Enternum = show.getText()+five.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
         String Enternum = show.getText()+six.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
      String Enternum = show.getText()+seven.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
         String Enternum = show.getText()+eight.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
         String Enternum = show.getText()+nine.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_nineActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
      String Enternum = show.getText()+zero.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_zeroActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        
         if (show.getText() != null && show.getText().equals(""))
        {
         
             JOptionPane.showMessageDialog(null ,"Input Number First!!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             Calculator.show();
        }
        
        else
         {
        
            firstnum = Double.parseDouble(show.getText());
            show.setText("");
            operations = "+";
         
         }
        
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        
         if (show.getText() != null && show.getText().equals(""))
        {
         
             JOptionPane.showMessageDialog(null ,"Input Number First!!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             Calculator.show();
        }
        
        else
         {
        
             firstnum = Double.parseDouble(show.getText());
             show.setText("");
             operations = "-";
             
         }
    }//GEN-LAST:event_minusActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
        
         if (show.getText() != null && show.getText().equals(""))
        {
         
             JOptionPane.showMessageDialog(null ,"Input Number First!!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             Calculator.show();
        }
        else
         {
            firstnum = Double.parseDouble(show.getText());
            show.setText("");
            operations = "*";
         }
    }//GEN-LAST:event_multActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
          
        if (show.getText() != null && show.getText().equals(""))
        {
         
             JOptionPane.showMessageDialog(null ,"Input Number First!!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             Calculator.show();
        }  
        else
        {
            firstnum = Double.parseDouble(show.getText());
            show.setText("");
            operations = "/";
            
        }
    }//GEN-LAST:event_divActionPerformed

    private void eqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqlActionPerformed
        
         if (show.getText() != null && show.getText().equals(""))
        {
         
             JOptionPane.showMessageDialog(null ,"Input Number First!!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             Calculator.show();
        }    
        
        else
         {
        
        String answer;
        secondnum = Double.parseDouble(show.getText());
        if(operations == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.2f",result);
            show.setText(answer);
        }
          else  if(operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.2f",result);
            show.setText(answer);
        }
           else  if(operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.2f",result);
            show.setText(answer);
        }
           else  if(operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.2f",result);
            show.setText(answer);
        }
           else  if(operations == "%")
        {
            result = firstnum % secondnum;
            answer = String.format("%.2f",result);
            show.setText(answer);
        }
        else
           {
               show.setText("Syntax Error!!");
           }
        
        
         }
        
    }//GEN-LAST:event_eqlActionPerformed

    private void periodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodActionPerformed
         String Enternum = show.getText()+period.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_periodActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        String Enternum = show.getText()+one.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
         String Enternum = show.getText()+two.getText();
        show.setText(Enternum);
    }//GEN-LAST:event_twoActionPerformed

    private void negaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negaActionPerformed
       
        if (show.getText() != null && show.getText().equals(""))
        {
         
             JOptionPane.showMessageDialog(null ,"Input Number First!!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             Calculator.show();
        }
        else
        {
            double ops = Double.parseDouble(String.valueOf(show.getText()));
            ops = ops * (-1);
            show.setText(String.valueOf(ops));  
        }
    }//GEN-LAST:event_negaActionPerformed

    private void sqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrActionPerformed
       
         if (show.getText() != null && show.getText().equals(""))
        {
         
             JOptionPane.showMessageDialog(null ,"Input Number First!!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             Calculator.show();
        }
        else
         {
        
            double value = Math.sqrt(Double.parseDouble(show.getText()));
            show.setText(Double.toString(value));
            
         }
    }//GEN-LAST:event_sqrActionPerformed

    private void three1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three1ActionPerformed
         
        if (show.getText() != null && show.getText().equals(""))
        {
         
             JOptionPane.showMessageDialog(null ,"Input Number First!!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             Calculator.show();
        }
        
        else
        {
            double Rsqr;
            double Fsqr = Double.parseDouble(show.getText());
            Rsqr = Fsqr * Double.parseDouble (show.getText());
            show.setText(Double.toString(Rsqr));
        }
    }//GEN-LAST:event_three1ActionPerformed

    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
        Calculator.show();
        cal.hide();
    }//GEN-LAST:event_calActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            Calculator.hide();
            
    }//GEN-LAST:event_formWindowOpened

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        
         
        DateFormat Fdate = dateChoser.getDateFormat();
        DateFormat r = new SimpleDateFormat("dd/MM/yy", Locale.getDefault());
        
        String s = String.valueOf(dateChoser.getText());
        Date fuck ;
            try {
                fuck = r.parse(s);
            } catch (ParseException e) {
            }
            
        String Rname;
        Rname = name.getText();
        
        labelR.show();
        labelR.setText(String.valueOf("Name: " + Rname + ".  " + "DOB: " + s));
        
        
        
    }//GEN-LAST:event_okActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed

    private void gerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerActionPerformed
       
        if (table.getText().trim().isEmpty()== false)
        {
             JOptionPane.showMessageDialog(null ,"Clear text first!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
        }
        if (txt.getText().trim().isEmpty())
        {
             JOptionPane.showMessageDialog(null ,"Input a number!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
        
        int b , i , m;
        b = Integer.parseInt (txt.getText());
        
        for ( i = 1 ; i <= 10 ; i++)
        {
            m = b * i ;
            table.append ( b + " * " + i + " = " + m + "\n");
        }
        txt.setText("");
        
        }
    }//GEN-LAST:event_gerActionPerformed

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        table.setText("");
        txt.setText("");
    }//GEN-LAST:event_clrActionPerformed

    private void txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyPressed
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
             JOptionPane.showMessageDialog(null ,"Numbers only!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             getToolkit().beep();
             txt.setText("");
        }
            
    }//GEN-LAST:event_txtKeyPressed

    private void txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyTyped
        
    }//GEN-LAST:event_txtKeyTyped

    private void showKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showKeyTyped
   
        
             JOptionPane.showMessageDialog(null ,"Invalid!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             getToolkit().beep();
             
                // TODO add your handling code here:
    }//GEN-LAST:event_showKeyTyped

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
      JOptionPane.showMessageDialog(null ,"Invalid!" , "ERROR!" , JOptionPane.INFORMATION_MESSAGE);
             getToolkit().beep();
    }//GEN-LAST:event_showMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calculator;
    private javax.swing.JButton cal;
    private javax.swing.JButton calClr;
    private javax.swing.JButton clr;
    private javax.swing.JLabel date;
    private datechooser.beans.DateChooserCombo dateChoser;
    private javax.swing.JButton div;
    private javax.swing.JButton eight;
    private javax.swing.JButton eql;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton ger;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelR;
    private javax.swing.JButton minus;
    private javax.swing.JButton mult;
    private javax.swing.JTextField name;
    private javax.swing.JButton nega;
    private javax.swing.JButton nine;
    private javax.swing.JButton ok;
    private javax.swing.JButton one;
    private javax.swing.JButton period;
    private javax.swing.JButton plus;
    private javax.swing.JButton seven;
    private javax.swing.JTextField show;
    private javax.swing.JButton six;
    private javax.swing.JButton sqr;
    private javax.swing.JTextArea table;
    private javax.swing.JButton three;
    private javax.swing.JButton three1;
    private javax.swing.JLabel time;
    private javax.swing.JButton two;
    private javax.swing.JTextField txt;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
