/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addnewstudent.java
 *
 * Created on Apr 11, 2019, 2:16:21 PM
 */
package registration;

import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import static registration.returnB.tfBorId;

/**
 *
 * @author Danzkie The Balbones
 */
public class addnewstudent extends javax.swing.JFrame {

    /** Creates new form addnewstudent */
    public com.mysql.jdbc.Connection cn;
    public Statement st;
    
    public addnewstudent() {
        initComponents();
    }
    DefaultTableModel dm;
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfSName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSAdd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfSCont = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfSId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfSCour = new javax.swing.JTextField();
        btnRe = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD NEW STUDENT");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Name:");

        tfSName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");

        tfSAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact No.:");

        tfSCont.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSCont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSContActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 204));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 0, 0));
        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID No.:");

        tfSId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSId.setEnabled(false);
        tfSId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSIdActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnUp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUp.setForeground(new java.awt.Color(0, 102, 0));
        btnUp.setText("Update");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Course:");

        tfSCour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSCour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSCour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSCourActionPerformed(evt);
            }
        });

        btnRe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRe.setForeground(new java.awt.Color(0, 0, 204));
        btnRe.setText("REFRESH");
        btnRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 0, 0));
        btnexit.setText("BACK");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfSName)
                                            .addComponent(tfSAdd)
                                            .addComponent(tfSCont, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfSId, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfSCour, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 108, Short.MAX_VALUE)
                                        .addComponent(btnAdd)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDel)))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnRe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnexit)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfSId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tfSCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfSCour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAdd)
                                    .addComponent(btnUp)
                                    .addComponent(btnDel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRe)
                                    .addComponent(btnexit))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

 public void ver() {
     
    try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bit?zeroDateTimeBehavior=convertToNull","root","");
            st = (Statement) cn.createStatement();
            //JOptionPane.showMessageDialog(null,"Connected");
        }
        catch (Exception e){
            //JOptionPane.showMessageDialog(null,e);
        }
 }
 
 
 public void addStud() {
     try {
         ver();
         
         String sql = "Insert into stud"
                + "(StudentName,Address,ContactNo,Course)"
                + "values (?,?,?,?)";
        PreparedStatement pst = cn.prepareStatement(sql);
        
        pst.setString(1, tfSName.getText());
        pst.setString(2, tfSAdd.getText());
        pst.setString(3, tfSCont.getText());
        pst.setString(4, tfSCour.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,"Student Added...");
        fetch();
        tfSName.setText("");
        tfSAdd.setText("");
        tfSCont.setText("");
        tfSCour.setText("");
        pst.close();
        
     }
     catch (Exception e) {
         JOptionPane.showMessageDialog(this, e.getMessage());
     }
 }
 public void delStud() {
     try {
         ver();
         
          String value = tfSId.getText();            
        
            String delsql = "DELETE FROM stud where ID =" + value ;
            PreparedStatement pst = cn.prepareStatement(delsql);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Deleted!");
            fetch();
            tfSId.setText("");
            tfSName.setText("");
            tfSAdd.setText("");
            tfSCont.setText("");
            tfSCour.setText("");
            pst.close();
    
     }
     catch (Exception e) {
         
     }
 }
 public void upStud() {
     try {
         
        ver();
        String value = (tfSId.getText());
        String sql = "UPDATE stud SET StudentName = ?, Address = ?, ContactNo = ?, Course = ? where ID = "+ value;
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, tfSName.getText());
        pst.setString(2, tfSAdd.getText());
        pst.setString(3, tfSCont.getText());
        pst.setString(4, tfSCour.getText());
        pst.execute();
        JOptionPane.showMessageDialog(this, "Updated Successfully!");                                       
        fetch(); 
        tfSId.setText("");
        tfSName.setText("");
        tfSAdd.setText("");
        tfSCont.setText("");
        tfSCour.setText("");
        pst.close();
         
     }
     catch (Exception e) {
         
     }
 }
 
 public void close() {
    this.setVisible(false);
    this.dispose();
}
public void fetch() {
    
    try {
        
        ver();
        
        String sql = "Select ID, StudentName, Address, ContactNo, Course from stud ORDER BY ID ASC" ;
        PreparedStatement pst = cn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        pst.close();
        
    }
    catch (Exception e) {
        
    }
}
public void table() {
     try {
        
        ver();
        
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        int row = jTable1.getSelectedRow();
        String value = (jTable1.getModel().getValueAt(row, 0).toString());
        
        String Gsql = "SELECT * FROM stud where ID =" + value ;
        PreparedStatement pst = cn.prepareStatement(Gsql);
        ResultSet rs = pst.executeQuery(); 
       
        if(rs.next()) {
             tfSId.setText(model.getValueAt(i,0).toString());
             tfSName.setText(model.getValueAt(i,1).toString());
             tfSAdd.setText(model.getValueAt(i,2).toString());
             tfSCont.setText(model.getValueAt(i,3).toString());
             tfSCour.setText(model.getValueAt(i,4).toString());
        }
        
    }
    catch (Exception e) {
        
    }
}
private void tfSContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSContActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tfSContActionPerformed

private void tfSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tfSNameActionPerformed

private void tfSIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSIdActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tfSIdActionPerformed

    private void tfSCourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSCourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSCourActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addStud();
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       fetch();
        btnUp.setVisible(false);
       btnDel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        table();
         btnAdd.setVisible(false);
        btnUp.setVisible(true);
        btnDel.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
     upStud();
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReActionPerformed
        btnAdd.setVisible(true);
         tfSId.setText("");
         tfSName.setText("");
         tfSAdd.setText("");
         tfSCont.setText("");
         tfSCour.setText("");
         btnUp.setVisible(false);
         btnDel.setVisible(false);
    }//GEN-LAST:event_btnReActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
       delStud();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        adminDash a = new adminDash();
        a.show();
        close();
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addnewstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addnewstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addnewstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addnewstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new addnewstudent().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnRe;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfSAdd;
    private javax.swing.JTextField tfSCont;
    private javax.swing.JTextField tfSCour;
    private javax.swing.JTextField tfSId;
    private javax.swing.JTextField tfSName;
    // End of variables declaration//GEN-END:variables
}
