/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SEARCH.java
 *
 * Created on Apr 11, 2019, 1:46:00 PM
 */
package registration;

import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author spyrax10
 */
public class SEARCH extends javax.swing.JFrame {

    /** Creates new form SEARCH */
    public com.mysql.jdbc.Connection cn;
    public Statement st;
    
    public SEARCH() {
        initComponents();
    }
    DefaultTableModel dm;
    
    public void ver() {
   
    try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bit?zeroDateTimeBehavior=convertToNull","root","");
            st = (Statement) cn.createStatement();
            //JOptionPane.showMessageDialog(null,"Connected");
        }
        catch (Exception e){
            //JOptionPane.showMessageDialog(null,e);
        }
    
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfSer = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfBId = new javax.swing.JTextField();
        tfBAuth = new javax.swing.JTextField();
        tfBTit = new javax.swing.JTextField();
        tfBShelf = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        tfSer.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfSer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSer.setText("Search by Book ID");
        tfSer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSerMouseClicked(evt);
            }
        });
        tfSer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSerKeyReleased(evt);
            }
        });

        btnsearch.setBackground(new java.awt.Color(0, 102, 0));
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel1.setText("BOOK ID NO.");

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel2.setText("AUTHOR:");

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel3.setText("BOOK TITLE:");

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel4.setText("SHELF:");

        tfBId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBId.setEnabled(false);
        tfBId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBIdActionPerformed(evt);
            }
        });

        tfBAuth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBAuthActionPerformed(evt);
            }
        });

        tfBTit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBTit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBTitActionPerformed(evt);
            }
        });

        tfBShelf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBShelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBShelfActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 204));
        btnAdd.setText("ADD BOOK");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUp.setForeground(new java.awt.Color(0, 102, 0));
        btnUp.setText("UPDATE BOOK");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 0, 0));
        btnDel.setText("DELETE BOOK");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBId)
                            .addComponent(tfBTit)
                            .addComponent(tfBShelf)
                            .addComponent(tfBAuth, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btnUp)
                        .addGap(54, 54, 54)
                        .addComponent(btnDel)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfBId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfBAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfBTit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfBShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDel)
                    .addComponent(btnUp)
                    .addComponent(btnAdd))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 0, 0));
        btnexit.setText("BACK");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnRef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRef.setForeground(new java.awt.Color(0, 0, 255));
        btnRef.setText("REFRESH");
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfSer, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRef)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnexit))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearch)
                    .addComponent(tfSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnexit))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRef)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void addBook() {
    
    
    try {
        
        ver();
        
        String sql = "Insert into book"
                + "(author,title,shelf)"
                + "values (?,?,?)";
        PreparedStatement pst = cn.prepareStatement(sql);
        
        pst.setString(1, tfBAuth.getText());
        pst.setString(2, tfBTit.getText());
        pst.setString(3, tfBShelf.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,"Book Added...");
        fetch();
        tfBId.setText("");
        tfBAuth.setText("");
        tfBTit.setText("");
        tfBShelf.setText("");
        pst.close();
        
    }
     catch (Exception e) {
         
     }
}
 public void search() {
         try {
             
             ver();
             
                String rsql = "SELECT * FROM book WHERE book_id=?"; 
                PreparedStatement pst = cn.prepareStatement(rsql);
                pst.setString(1,tfSer.getText());
                ResultSet rs = pst.executeQuery(); 
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(this, e.getMessage());
         }
     }
public void close() {
    this.setVisible(false);
    this.dispose();
}
public void fetch() {
    
    try {
        
        ver();
        
        String sql = "Select book_id, author, title, shelf from book ORDER BY book_id ASC" ;
        PreparedStatement pst = cn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        pst.close();
        
    }
    catch (Exception e) {
        
    }
}
public void delBook() {
    try {
        
        ver();
        
            String value = tfBId.getText();            
        
            String delsql = "DELETE FROM book where book_id =" + value ;
            PreparedStatement pst = cn.prepareStatement(delsql);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Deleted!");
            fetch();
            tfBId.setText("");
            tfBAuth.setText("");
            tfBTit.setText("");
            tfBShelf.setText("");
            pst.close();
    }
    catch (Exception e) {
        
    }
}
public void upBook() {
    try {
        
        ver();
        String value = (tfBId.getText());
        String sql = "UPDATE book SET author = ?, title = ?, shelf = ? where book_id = "+ value;
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, tfBAuth.getText());
        pst.setString(2, tfBTit.getText());
        pst.setString(3, tfBShelf.getText());
        pst.execute();
        JOptionPane.showMessageDialog(this, "Updated Successfully!");                                       
        fetch(); 
        tfBId.setText("");
        tfBAuth.setText("");
        tfBTit.setText("");
        tfBShelf.setText("");
        pst.close();
    }
    catch (Exception e) {
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
public void table() {
    try {
        
        ver();
        
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        int row = jTable1.getSelectedRow();
        String value = (jTable1.getModel().getValueAt(row, 0).toString());
        
        String Gsql = "SELECT * FROM book where book_id =" + value ;
        PreparedStatement pst = cn.prepareStatement(Gsql);
        ResultSet rs = pst.executeQuery(); 
       
        if(rs.next()) {
             tfBId.setText(model.getValueAt(i,0).toString());
             tfBAuth.setText(model.getValueAt(i,1).toString());
             tfBTit.setText(model.getValueAt(i,2).toString());
             tfBShelf.setText(model.getValueAt(i,3).toString());
        }
        
    }
    catch (Exception e) {
        
    }
}

private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
    search();
}//GEN-LAST:event_btnsearchActionPerformed

private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
    adminDash a = new adminDash();
    a.show();
    close();
}//GEN-LAST:event_btnexitActionPerformed

private void tfBIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBIdActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tfBIdActionPerformed

private void tfBAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBAuthActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tfBAuthActionPerformed

private void tfBTitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBTitActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tfBTitActionPerformed

private void tfBShelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBShelfActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tfBShelfActionPerformed

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
addBook();
}//GEN-LAST:event_btnAddActionPerformed

private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
    upBook();
}//GEN-LAST:event_btnUpActionPerformed

private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
    delBook();
}//GEN-LAST:event_btnDelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
       fetch();
       btnUp.setVisible(false);
       btnDel.setVisible(false) ;
      
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        table();
        btnAdd.setVisible(false);
        btnUp.setVisible(true);
        btnDel.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
         
         btnAdd.setVisible(true);
         tfBId.setText("");
         tfBAuth.setText("");
         tfBTit.setText("");
         tfBShelf.setText("");
         btnUp.setVisible(false);
         btnDel.setVisible(false);
         tfSer.setText("");
         fetch();
         
    }//GEN-LAST:event_btnRefActionPerformed

    private void tfSerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSerMouseClicked
        tfSer.setText("");
    }//GEN-LAST:event_tfSerMouseClicked

    private void tfSerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSerKeyReleased
        search();
    }//GEN-LAST:event_tfSerKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SEARCH().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdd;
    public static javax.swing.JButton btnDel;
    public static javax.swing.JButton btnRef;
    public static javax.swing.JButton btnUp;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfBAuth;
    private javax.swing.JTextField tfBId;
    private javax.swing.JTextField tfBShelf;
    private javax.swing.JTextField tfBTit;
    private javax.swing.JTextField tfSer;
    // End of variables declaration//GEN-END:variables
}
